FROM jrottenberg/ffmpeg:6.1-alpine

USER root

RUN apk add --no-cache python3 yt-dlp

COPY src/encoder/start_encoder.sh /start_encoder.sh
RUN chmod +x /start_encoder.sh

ENTRYPOINT ["/start_encoder.sh"] 