
services:
  encoder:
    build:
      context: .
      dockerfile: Dockerfile.encoder
    container_name: encoder
    environment:
      # - YOUTUBE_URL=https://www.youtube.com/watch?v=cb12KmMMDJA
      - YOUTUBE_URL=https://www.youtube.com/watch?v=5f__Ls4_VYQ # URL del video de YouTube a transmitir
    networks:
      streaming:
        ipv4_address: 172.28.1.10

  packager:
    build:
      context: .
      dockerfile: Dockerfile.packager
    container_name: packager
    networks:
      streaming:
        ipv4_address: 172.28.1.11
    volumes:
      - ./temp-data/packager-output:/media/www/ # Directorio donde se guardan los segmentos y manifiesto MPD
    ports:
      - "38882:80"
    environment: # Parámetros del Shaka Packager
      PACKAGER_PARAMS: >
        input=udp://0.0.0.0:40000,stream=audio,init_segment=/media/www/audio/audio_init.mp4,segment_template=/media/www/audio/audio_$$Number$$.m4s
        input=udp://0.0.0.0:40000,stream=video,init_segment=/media/www/video/h264_360p_init.mp4,segment_template=/media/www/video/h264_360p_$$Number$$.m4s
        --mpd_output /media/www/manifest.mpd

  player:
    build:
      context: .
      dockerfile: Dockerfile.player
    container_name: player
    ports:
      - "38880:80"
    environment:
      # - MANIFEST_URL=http://localhost:38882/manifest.mpd
      - MANIFEST_URL=https://encoder001.hostclick.us/encuentro_test/index.mpd # URL del manifiesto MPD a reproducir
    networks:
      - streaming

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: dashboard
    volumes:
      - ./logs:/app/stream_analysis # Directorio donde estan los logs del análisis de monitor
    ports:
      - "38881:8081"
    environment:
      - MANIFEST_URL=http://packager:80/manifest.mpd
    networks:
      - streaming
    depends_on:
      - packager
    command: ["python3", "/app/dashboard.py"]

  monitor:
    build:
      context: .
      dockerfile: Dockerfile.monitor
    container_name: monitor
    volumes:
      - ./logs:/app/stream_analysis
    environment:
      - MANIFEST_URL=https://encoder001.hostclick.us/encuentro_test/index.mpd # URL del manifiesto MPD a analizar. Para usar la salida del packager, usar: http://packager:80/manifest.mpd sue puede usar http://packager:80/manifest.mpd
      - MONITOR_INTERVAL=30
    networks:
      - streaming

  

networks:
  streaming:
    ipam:
      config:
        - subnet: 172.28.1.0/24