
services:
  encoder:
    build:
      context: .
      dockerfile: Dockerfile.encoder
  #   #image: linuxserver/ffmpeg:7.1.1
  # encoder:
  #   image: jrottenberg/ffmpeg:6.1-alpine
    container_name: encoder
    networks:
      streaming:
        ipv4_address: 172.28.1.10
    volumes:
      - ./media/www:/media/www
      # - ./start_encoder.sh:/start_encoder.sh

  packager:
    image: google/shaka-packager:v3.4.2
    container_name: packager
    volumes:
      # - ./media/www:/media/www
      - ./media:/media
    networks:
      streaming:
        ipv4_address: 172.28.1.11
    tty: true
    # depends_on:
    #   - encoder
    command:
      - packager
#      - "input=udp://0.0.0.0:40000,stream=audio,init_segment=audio_init.mp4,segment_template=audio_$$Number$$.m4s"
      # - "input=udp://0.0.0.0:40000,stream=video,init_segment=h264_360p_init.mp4,segment_template=h264_360p_$$Number$$.m4s"

      - "input=udp://0.0.0.0:40000,stream=audio,init_segment=/media/www/audio_init.mp4,segment_template=/media/www/audio_$$Number$$.m4s"
      - "input=udp://0.0.0.0:40000,stream=video,init_segment=/media/www/h264_360p_init.mp4,segment_template=/media/www/h264_360p_$$Number$$.m4s"
  
      # - --segment_duration
      # - "5"
      - --mpd_output
      - /media/www/manifest.mpd

  player:
    image: nginx:alpine
    container_name: player
    volumes:
      - ./media/www:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    networks:
      - streaming

networks:
  streaming:
    ipam:
      config:
        - subnet: 172.28.1.0/24