
services:
  encoder:
    build:
      context: .
      dockerfile: Dockerfile.encoder
  #   #image: linuxserver/ffmpeg:7.1.1
  # encoder:
  #   image: jrottenberg/ffmpeg:6.1-alpine
    container_name: encoder
    networks:
      streaming:
        ipv4_address: 172.28.1.10
    volumes:
      - ./media/www:/media/www
      # - ./start_encoder.sh:/start_encoder.sh

  packager:
    image: google/shaka-packager:v3.4.2
    container_name: packager
    volumes:
      # - ./media/www:/media/www
      - ./media:/media
    networks:
      streaming:
        ipv4_address: 172.28.1.11
    tty: true
    # depends_on:
    #   - encoder
    command:
      - packager
#      - "input=udp://0.0.0.0:40000,stream=audio,init_segment=audio_init.mp4,segment_template=audio_$$Number$$.m4s"
      # - "input=udp://0.0.0.0:40000,stream=video,init_segment=h264_360p_init.mp4,segment_template=h264_360p_$$Number$$.m4s"

      - "input=udp://0.0.0.0:40000,stream=audio,init_segment=/media/www/output/audio/audio_init.mp4,segment_template=/media/www/output/audio/audio_$$Number$$.m4s"
      - "input=udp://0.0.0.0:40000,stream=video,init_segment=/media/www/output/video/h264_360p_init.mp4,segment_template=/media/www/output/video/h264_360p_$$Number$$.m4s"
  
      # - --segment_duration
      # - "5"
      - --mpd_output
      - /media/www/output/manifest.mpd

  player:
    image: nginx:alpine
    container_name: player
    volumes:
      - ./media/www:/usr/share/nginx/html:rw
    ports:
      - "38880:80"
    networks:
      - streaming

  monitor:
    build:
      context: .
      dockerfile: Dockerfile.monitor
    container_name: monitor
    volumes:
      - ./media:/media
      - ./logs:/app/logs
      - ./quality_analyzer.sh:/app/quality_analyzer.sh:ro
      - ./stream_monitor.py:/app/stream_monitor.py:ro
    ports:
      - "38881:8081"
    environment:
      - MANIFEST_URL=http://player:80/output/manifest.mpd
      - MONITOR_INTERVAL=30
      - LOG_LEVEL=INFO
    networks:
      - streaming
    depends_on:
      - packager
    command: ["python3", "/app/stream_monitor.py", "http://player:80/output/manifest.mpd", "-i", "30", "-o", "/app/logs/stream_quality.json"]

networks:
  streaming:
    ipam:
      config:
        - subnet: 172.28.1.0/24