# Configuración del Sistema de Monitoreo de Calidad de Streaming

# Configuración general
general:
  log_level: INFO
  log_retention_days: 7
  timezone: UTC

# Configuración del monitor de stream
stream_monitor:
  interval_seconds: 30
  timeout_seconds: 10
  max_retries: 3
  manifest_url: "http://packager:8080/manifest.mpd"
  
  # Métricas a monitorear
  metrics:
    - bitrate
    - resolution
    - buffer_health
    - network_latency
    - errors
    - adaptation_events

# Configuración del analizador de calidad
quality_analyzer:
  # Segmentos a analizar
  max_segments_per_run: 5
  analyze_audio: true
  analyze_video: true
  
  # Métricas de calidad
  quality_metrics:
    - psnr
    - ssim
    - signalstats
    - audio_analysis
    - artifact_detection
  
  # Umbrales de alerta
  thresholds:
    psnr_min: 30.0
    ssim_min: 0.90
    audio_level_min: -30.0
    buffer_min_seconds: 2.0

# Configuración de alertas
alerts:
  enabled: true
  email:
    smtp_server: ""
    smtp_port: 587
    username: ""
    password: ""
    recipients: []
  
  # Condiciones de alerta
  conditions:
    - name: "Low Quality"
      metric: "psnr"
      operator: "<"
      value: 30.0
      severity: "warning"
    
    - name: "Buffer Underrun"
      metric: "buffer_health"
      operator: "<"
      value: 2.0
      severity: "critical"
    
    - name: "Network Error"
      metric: "network_status"
      operator: "=="
      value: "error"
      severity: "critical"

# Configuración del dashboard
dashboard:
  port: 8081
  host: "0.0.0.0"
  refresh_interval: 5000  # ms
  max_data_points: 1000
  
  # Gráficos disponibles
  charts:
    - name: "Bitrate Over Time"
      type: "line"
      metrics: ["bitrate"]
    
    - name: "Buffer Health"
      type: "gauge"
      metrics: ["buffer_health"]
    
    - name: "Quality Metrics"
      type: "bar"
      metrics: ["psnr", "ssim"]

# Configuración de exportación de datos
export:
  enabled: true
  formats:
    - json
    - csv
    - prometheus
  
  # Configuración de Prometheus
  prometheus:
    enabled: false
    port: 9090
    metrics_path: "/metrics"

# Configuración de VMAF
vmaf:
  enabled: true
  model_path: "/usr/local/share/vmaf/models/vmaf_v0.6.1.pkl"
  reference_required: true
  
  # Configuración de análisis
  analysis:
    frame_rate: 30
    pixel_format: "yuv420p"
    bit_depth: 8

# Configuración de FFmpeg
ffmpeg:
  # Filtros para detección de problemas
  filters:
    black_detect:
      duration: 0.1
      pixel_threshold: 0.1
    
    signalstats:
      stats: 1
      out: 1
    
    ssim:
      stats_file: "ssim.log"
    
    psnr:
      stats_file: "psnr.log"

# Configuración de limpieza automática
cleanup:
  enabled: true
  schedule: "0 2 * * *"  # Diario a las 2 AM
  retention:
    logs_days: 7
    analysis_days: 30
    reports_days: 90 