#!/bin/bash
echo "=== Herramientas de Monitoreo de Calidad de Streaming ==="
echo "FFmpeg: $(ffmpeg -version | head -1)"
echo "Python: $(python3 --version)"
echo "VMAF: $(vmaf --version 2>/dev/null || echo "No instalado - requiere Python 3.10+")"
echo "MP4Box: $(mp4box -version 2>/dev/null || echo "No instalado - requiere GPAC")"
echo "Bento4: $(mp4dash --help 2>/dev/null | head -1 || echo "No instalado - se puede compilar manualmente")"
echo ""
echo "Scripts disponibles:"
echo "- /app/quality_analyzer.sh: Análisis de calidad de video"
echo "- /app/stream_monitor.py: Monitor de streams DASH/HLS"
echo ""
echo "Ejemplos de uso:"
echo "  ./quality_analyzer.sh input.mp4 output_dir"
echo "  python3 stream_monitor.py http://localhost:8080/manifest.mpd -i 30"
echo "  ffmpeg -i input.mp4 -vf ssim=stats_file=ssim.log -f null -"
echo "  vmaf -r reference.mp4 -d input.mp4 -o vmaf_output.xml"
echo ""
exec "$@" 