#!/bin/bash
echo "=== Herramientas de Monitoreo de Calidad de Streaming ==="
echo "FFmpeg: $(ffmpeg -version | head -1)"
echo "Python: $(python3 --version)"
echo "VMAF: $(vmaf --version 2>/dev/null || echo "No instalado - requiere Python 3.10+")"
echo "MP4Box: $(mp4box -version 2>/dev/null || echo "No instalado - requiere GPAC")"
echo "Bento4: $(mp4dash --help 2>/dev/null | head -1 || echo "No instalado - se puede compilar manualmente")"
echo ""
echo "Scripts disponibles:"
echo "- /app/quality_analyzer.sh: Análisis de calidad de video (archivos)"
echo "- /app/stream_monitor.py: Monitor básico de streams DASH/HLS"
echo ""
echo "=== HERRAMIENTAS DE ANÁLISIS AVANZADO ==="
echo "- /app/stream_quality_analyzer.py: Análisis de calidad de streams en tiempo real"
echo "- /app/stream_latency_analyzer.py: Análisis de latencia y buffering"
echo "- /app/stream_adaptation_analyzer.py: Análisis de adaptación de bitrate"
echo "- /app/stream_analysis_suite.py: Suite completa de análisis"
echo "- /app/test_tools.py: Script de prueba de herramientas"
echo ""
echo "Ejemplos de uso:"
echo "  # Análisis básico de archivos:"
echo "  ./quality_analyzer.sh input.mp4 output_dir"
echo "  # Monitor básico de streams:"
echo "  python3 stream_monitor.py http://localhost:8080/manifest.mpd -i 30"
echo "  # Suite completa de análisis:"
echo "  python3 stream_analysis_suite.py http://player:80/output/manifest.mpd -i 30"
echo "  # Análisis individual:"
echo "  python3 stream_quality_analyzer.py http://player:80/output/manifest.mpd -i 30"
echo "  python3 stream_latency_analyzer.py http://player:80/output/manifest.mpd -i 5"
echo "  python3 stream_adaptation_analyzer.py http://player:80/output/manifest.mpd -i 10"
echo ""
echo "  # Herramientas FFmpeg:"
echo "  ffmpeg -i input.mp4 -vf ssim=stats_file=ssim.log -f null -"
echo "  vmaf -r reference.mp4 -d input.mp4 -o vmaf_output.xml"
echo ""
exec "$@" 